import type {
  CurrencyCode,
  LocationId,
  ProjectSizeId,
  QualityId,
} from "@/types";

export const categories = [
  {
    id: "web",
    name: "Website development",
    shortName: "Web development",
    description: "Marketing sites, portfolios and business websites.",
    icon: "code",
    base: 5200,
    hours: 190,
    weeks: 5,
    range: "$3k – $12k",
    example:
      "I need a responsive business website with a modern design, contact form and basic SEO.",
  },
  {
    id: "mobile",
    name: "Mobile application",
    shortName: "Mobile app",
    description: "Native and cross-platform apps for iOS and Android.",
    icon: "smartphone",
    base: 9800,
    hours: 340,
    weeks: 8,
    range: "$7k – $28k",
    example:
      "I need a cross-platform fitness app with user profiles, subscriptions and progress tracking.",
  },
  {
    id: "ecommerce",
    name: "Ecommerce development",
    shortName: "Ecommerce",
    description: "Online stores, payments, inventory and product pages.",
    icon: "shopping-bag",
    base: 7200,
    hours: 245,
    weeks: 6,
    range: "$5k – $17k",
    example:
      "I need an ecommerce website for a clothing brand with online payments, customer accounts and about 500 products.",
  },
  {
    id: "design",
    name: "UI and UX design",
    shortName: "UI/UX design",
    description: "Product research, wireframes, prototypes and visual design.",
    icon: "palette",
    base: 3400,
    hours: 115,
    weeks: 3,
    range: "$2k – $8k",
    example:
      "I need a complete UI and UX design for a budgeting mobile app, including research and a clickable prototype.",
  },
  {
    id: "seo",
    name: "Search engine optimization",
    shortName: "SEO",
    description: "Technical SEO, content strategy and search improvements.",
    icon: "search",
    base: 2100,
    hours: 70,
    weeks: 3,
    range: "$1.2k – $5k",
    example:
      "I need technical SEO and a three-month content plan to improve organic traffic for my SaaS website.",
  },
  {
    id: "social",
    name: "Social media management",
    shortName: "Social media",
    description: "Content calendars, publishing and monthly reporting.",
    icon: "megaphone",
    base: 2300,
    hours: 80,
    weeks: 4,
    range: "$1.5k – $6k",
    example:
      "I need social media management for a small fashion brand, with 12 posts per month and monthly reports.",
  },
  {
    id: "branding",
    name: "Branding and graphic design",
    shortName: "Branding",
    description: "Visual identities, logos and brand guidelines.",
    icon: "pen-tool",
    base: 3600,
    hours: 105,
    weeks: 4,
    range: "$1.8k – $8k",
    example:
      "I need a complete visual identity for a new coffee brand, including logo, color palette and brand guide.",
  },
  {
    id: "ai",
    name: "AI solutions",
    shortName: "AI solutions",
    description: "AI assistants, automations and custom integrations.",
    icon: "bot",
    base: 10500,
    hours: 330,
    weeks: 8,
    range: "$8k – $32k",
    example:
      "I need an AI customer support assistant that connects to our knowledge base and Shopify store.",
  },
] as const;

export const locations = [
  {
    id: "us",
    country: "United States",
    city: "New York",
    currency: "USD",
    multiplier: 1.2,
    taxRate: 0.08875,
  },
  {
    id: "ca",
    country: "Canada",
    city: "Toronto",
    currency: "CAD",
    multiplier: 1,
    taxRate: 0.13,
  },
  {
    id: "uk",
    country: "United Kingdom",
    city: "London",
    currency: "GBP",
    multiplier: 0.92,
    taxRate: 0.2,
  },
  {
    id: "ae",
    country: "United Arab Emirates",
    city: "Dubai",
    currency: "AED",
    multiplier: 1.02,
    taxRate: 0.05,
  },
  {
    id: "pk",
    country: "Pakistan",
    city: "Karachi",
    currency: "PKR",
    multiplier: 0.34,
    taxRate: 0.05,
  },
  {
    id: "in",
    country: "India",
    city: "Mumbai",
    currency: "INR",
    multiplier: 0.3,
    taxRate: 0.18,
  },
  {
    id: "au",
    country: "Australia",
    city: "Sydney",
    currency: "AUD",
    multiplier: 1.08,
    taxRate: 0.1,
  },
  {
    id: "de",
    country: "Germany",
    city: "Berlin",
    currency: "EUR",
    multiplier: 0.98,
    taxRate: 0.19,
  },
  {
    id: "sg",
    country: "Singapore",
    city: "Singapore",
    currency: "SGD",
    multiplier: 1.04,
    taxRate: 0.09,
  },
  {
    id: "ng",
    country: "Nigeria",
    city: "Lagos",
    currency: "NGN",
    multiplier: 0.28,
    taxRate: 0.075,
  },
] as const;

export const projectSizes = [
  {
    id: "small",
    name: "Focused",
    description: "A smaller scope with essential features",
    example: "Landing page or one core workflow",
    multiplier: 0.72,
    weekFactor: 0.75,
  },
  {
    id: "medium",
    name: "Standard",
    description: "A balanced project with the usual features",
    example: "Several screens and integrations",
    multiplier: 1,
    weekFactor: 1,
  },
  {
    id: "large",
    name: "Complex",
    description: "A larger scope with advanced requirements",
    example: "Multiple workflows, roles and integrations",
    multiplier: 1.58,
    weekFactor: 1.45,
  },
] as const;

export const qualityOptions = [
  {
    id: "essential",
    name: "Essential",
    description: "Reliable, efficient and budget-conscious",
    multiplier: 0.82,
    weekFactor: 0.9,
  },
  {
    id: "standard",
    name: "Standard",
    description: "A strong balance of quality and value",
    multiplier: 1,
    weekFactor: 1,
  },
  {
    id: "premium",
    name: "Premium",
    description: "More polish, scale and customization",
    multiplier: 1.38,
    weekFactor: 1.2,
  },
] as const;

export const allCurrencies = [
  "USD",
  "CAD",
  "GBP",
  "AED",
  "PKR",
  "INR",
  "AUD",
  "EUR",
  "SGD",
  "NGN",
  "JPY",
  "CNY",
  "KRW",
  "BRL",
  "MXN",
  "ZAR",
  "SAR",
  "CHF",
  "SEK",
  "NOK",
] as const;

export const USD_RATES: Record<CurrencyCode, number> = {
  USD: 1,
  CAD: 1.37,
  GBP: 0.75,
  AED: 3.67,
  PKR: 280,
  INR: 88,
  AUD: 1.52,
  EUR: 0.86,
  SGD: 1.29,
  NGN: 1500,
  JPY: 148,
  CNY: 7.1,
  KRW: 1400,
  BRL: 5.4,
  MXN: 18.5,
  ZAR: 17.5,
  SAR: 3.75,
  CHF: 0.8,
  SEK: 9.4,
  NOK: 10,
};
